version: '3.1'
services:
  imdb-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
      - ORACLE_ALLOW_REMOTE=true 
      - DISABLE_OOB=ON
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./imdb-src/data:/opt/oracle/oradata
      - ./imdb-src/backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
  imdb-setup:
    build: ./imdb-src/setup
    depends_on:
      - imdb-db
    environment:
      - URL=imdb-db
      - PORT=1521
      - ORACLE_SID=ORCLCDB
      - ORACLE_PWD=Oracle_123
      - ORACLE_USER=system
      - KEEP_CACHE=yes
      - PYTHONUNBUFFERED=1
    volumes:
      - ./imdb-src/setup/cache:/app/cache
      - ./cassandra/ETL/cache:/cassandra/cache
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
      - 9842:9842
    volumes:
      - ./cassandra/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=imdb-decen
      - CASSANDRA_START_RPC=true
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
  #cassandra-upload:
  #  build: ./cassandra/ETL
  #  depends_on:
  #    - imdb-setup
  #    - cassandra
  #  environment:
  #    - URL=imdb-db
  #    - PORT=1521
  #    - ORACLE_SID=ORCLCDB
  #    - ORACLE_PWD=Oracle_123
  #    - ORACLE_USER=system
  #    - NODES=127.0.0.1,cassandra,localhost
  #    - PYTHONUNBUFFERED=1
  #  volumes:
  #    - ./cassandra/ETL/cache:/app/cache